return function()
    local route = {}
    local function makeWaypoint(x, y, z)
        local part = Instance.new("Part")
        part.Anchored, part.CanCollide, part.Transparency = true, false, 1
        part.Size = Vector3.new(1, 1, 1)
        part.Position = Vector3.new(x, y, z)
        part.Parent = workspace
        return part
    end

    route[#route + 1] = workspace.Towers:GetChildren()[12]:GetChildren()[1]:GetChildren()[2]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[64]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[33]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[72]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[76]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[78]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[87]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[90]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[93]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[92]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[102]
    route[#route + 1] = workspace.ClientParts:GetChildren()[32]:GetChildren()[2]
    route[#route + 1] = workspace.ClientParts:GetChildren()[32]:GetChildren()[3]
    route[#route + 1] = workspace.ClientParts:GetChildren()[32]:GetChildren()[4]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[105]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[131]
    route[#route + 1] = workspace.ClientParts:GetChildren()[34]:GetChildren()[1]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[115]
    route[#route + 1] = workspace.ClientParts:GetChildren()[33]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[19]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[17]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[18]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[21]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[20]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[157]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[161]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[147]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[23]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[208]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[210]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[181]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[202]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[204]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[221]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[226]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[247]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[237]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[233]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[238]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[246]
    route[#route + 1] = workspace.ClientParts:GetChildren()[41]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[41]:GetChildren()[2]
    route[#route + 1] = workspace.ClientParts:GetChildren()[41]:GetChildren()[3]
    route[#route + 1] = workspace.ClientParts:GetChildren()[41]:GetChildren()[4]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[253]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[256]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[266]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[299]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[329]
    route[#route + 1] = makeWaypoint(1049.185, 238.466, -384.512)
    route[#route + 1] = makeWaypoint(1051.323, 238.466, -383.631)
    route[#route + 1] = makeWaypoint(1053.188, 238.466, -382.389)
    route[#route + 1] = makeWaypoint(1054.114, 238.466, -379.436)
    route[#route + 1] = makeWaypoint(1055.139, 238.466, -377.693)
    route[#route + 1] = makeWaypoint(1054.943, 238.466, -375.614)
    route[#route + 1] = makeWaypoint(1054.611, 238.466, -373.408)
    route[#route + 1] = makeWaypoint(1054.272, 238.466, -370.990)
    route[#route + 1] = makeWaypoint(1053.666, 238.466, -369.443)
    route[#route + 1] = makeWaypoint(1054.130, 238.466, -367.271)
    route[#route + 1] = makeWaypoint(1053.020, 238.466, -363.733)
    route[#route + 1] = makeWaypoint(1050.248, 238.466, -360.637)
    route[#route + 1] = makeWaypoint(1046.891, 238.466, -359.931)
    route[#route + 1] = makeWaypoint(1043.545, 238.466, -360.078)
    route[#route + 1] = makeWaypoint(1040.622, 238.466, -360.920)
    route[#route + 1] = workspace.ClientParts:GetChildren()[45]:GetChildren()[3]
    route[#route + 1] = workspace.ClientParts:GetChildren()[45]:GetChildren()[2]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[45]:GetChildren()[2]:GetChildren()[4]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[417]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[292]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[298]
    route[#route + 1] = workspace.ClientParts:GetChildren()[46]:GetChildren()[1]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[442]
    route[#route + 1] = makeWaypoint(1075.967, 293.174, -356.559)
    route[#route + 1] = makeWaypoint(1075.352, 292.796, -361.643)
    route[#route + 1] = makeWaypoint(1068.760, 292.796, -366.278)
    route[#route + 1] = makeWaypoint(1067.697, 292.752, -372.803)
    route[#route + 1] = makeWaypoint(1073.187, 292.796, -384.057)
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[441]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[296]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[39]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[40]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[48]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[43]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[50]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[473]
    route[#route + 1] = workspace.ClientParts:GetChildren()[23]:GetChildren()[7]
    route[#route + 1] = workspace.ClientParts:GetChildren()[23]:GetChildren()[5]
    route[#route + 1] = workspace.ClientParts:GetChildren()[23]:GetChildren()[3]
    route[#route + 1] = workspace.ClientParts:GetChildren()[23]:GetChildren()[2]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[479]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[625]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[672]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[674]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[641]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[655]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[657]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[649]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[670]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[639]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[57]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[52]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[501]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[500]
    route[#route + 1] = makeWaypoint(987.207, 396.699, -417.541)
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[685]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[508]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[485]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[488]
    route[#route + 1] = makeWaypoint(986.207, 400.699, -328.540)
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[725]
    route[#route + 1] = makeWaypoint(997.707, 381.699, -377.040)
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[585]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[584]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[498]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[487]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[522]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[526]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[600]
    route[#route + 1] = workspace.ClientParts:GetChildren()[49]:GetChildren()[1]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[84]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[633]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[634]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[629]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[533]
    route[#route + 1] = workspace.ClientParts:GetChildren()[60]:GetChildren()[1]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[677]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[719]
    route[#route + 1] = workspace.ClientParts:GetChildren()[63]:GetChildren()[10]
    route[#route + 1] = workspace.ClientParts:GetChildren()[63]:GetChildren()[6]
    route[#route + 1] = workspace.ClientParts:GetChildren()[63]:GetChildren()[3]
    route[#route + 1] = workspace.ClientParts:GetChildren()[64]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[65]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[525]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[73]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[74]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[80]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[77]
    route[#route + 1] = workspace.ClientParts:GetChildren()[51]:GetChildren()[3]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[836]
    route[#route + 1] = workspace.ClientParts:GetChildren()[62]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[70]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[850]
    route[#route + 1] = workspace.ClientParts:GetChildren()[24]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[25]:GetChildren()[2]
    route[#route + 1] = makeWaypoint(1058.556, 494.000, -410.917)
    route[#route + 1] = makeWaypoint(1053.664, 490.000, -411.568)
    route[#route + 1] = makeWaypoint(1057.593, 490.000, -400.723)
    route[#route + 1] = makeWaypoint(1062.034, 490.000, -397.560)
    route[#route + 1] = makeWaypoint(1068.201, 490.000, -396.089)
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[742]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[98]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[91]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[118]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[122]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[128]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[124]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[133]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[109]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[889]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[110]
    route[#route + 1] = workspace.ClientParts:GetChildren()[11]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[106]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[138]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[158]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[145]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[149]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[142]
    route[#route + 1] = workspace.ClientParts:GetChildren()[17]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[155]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[159]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[160]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[152]
    route[#route + 1] = workspace.ClientParts:GetChildren()[18]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[918]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[767]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[774]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[988]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[57]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[54]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[55]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[14]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[10]
    route[#route + 1] = workspace.ClientParts:GetChildren()[20]:GetChildren()[1]
    route[#route + 1] = workspace.ClientParts:GetChildren()[6]:GetChildren()[2]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[192]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[63]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[190]
    route[#route + 1] = makeWaypoint(1063.850, 596.794, -400.894)
    route[#route + 1] = makeWaypoint(1074.786, 596.794, -409.955)
    route[#route + 1] = makeWaypoint(1067.800, 596.785, -410.443)
    route[#route + 1] = makeWaypoint(1059.090, 596.794, -411.345)
    route[#route + 1] = makeWaypoint(1065.224, 596.794, -413.991)
    route[#route + 1] = makeWaypoint(1072.034, 596.794, -407.544)
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[139]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[163]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[146]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[2]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[1064]
    route[#route + 1] = workspace.ClientParts:GetChildren()[12]:GetChildren()[1]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[819]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[4]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[1081]
    route[#route + 1] = workspace.ClientParts:GetChildren()[50]:GetChildren()[4]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[1011]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[1009]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[1003]
    route[#route + 1] = workspace.ClientParts:GetChildren()[6]:GetChildren()[1]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[983]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[980]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[170]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[167]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[166]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[168]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[164]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[165]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[1097]
    route[#route + 1] = workspace.ClientParts:GetChildren()[3]
    route[#route + 1] = workspace.ClientParts:GetChildren()[8]:GetChildren()[140]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[947]
    route[#route + 1] = workspace.Towers["SoBJ"].Obby:GetChildren()[955]
    route[#route + 1] = workspace.Towers:GetChildren()[12]:GetChildren()[3]

    return route
end