local Categories = {
    Ring0 = 9070958509,
    Ring1 = 9070657865,
    Ring2 = 9070979698,
    Ring3 = 9070980083,
    Ring4 = 9070980555,
    Ring5 = 9070980846,
    Ring6 = 9070981164,
    Ring7 = 9070981409,
    Ring8 = 8700866519,
    Ring9 = 9070982474,
    Zone1 = 9071001075,
    Zone2 = 9071001366,
    Zone3 = 9071001563,
    Zone7 = 9071002677,
    Zone8 = 9071002915,
    Zone9 = 9071004505,

    ForgottenRidge = 9070954594,
    GardenOfEeshol = 9070960075,

    -- A category may map to one place id or a list of them. Pit of Misery exists in the
    -- original EToH place AND in "The Eternal Abyss" (15873244701) + its Pit of Misery
    -- subplace (121814103864070) -- the same towers are present in all of them.
    ["Pit-of-Misery"] = { 15639952229, 15873244701, 121814103864070 },
    TheEternalAbyss = 15873244701,
    TimelessManor = 131042387601353,
    ["100M-Event-Replay"] = 115856553162061,
    BIOUMS = 111393548264972,

    -- Merged from cslp1/Project-EToH-Script
    ArcaneArea = 9070944007,
    AshenTowerworks = 14399266686,
    ElysianFields = 95241871632790,
    HeccfireDepths = 9070963935,
    LegacyFortress = 116826560849733,
    LostRiver = 9945448769,
    ParadiseAtoll = 9070975342,
    SilentAbyss = 11916533264,
    SteelspireHorizon = 18538513621,
    SummitOfMemories = 90713610472463,
    TheDoghouse = 16976865869,
    XLRing1 = 13228556826,
    XLRing3 = 13654432865,
    XLRing5 = 80018210783565,
    Zone4 = 9071001883,
    Zone5 = 9071002104,
    Zone6 = 9071002463,
    Zone10 = 9071004898,
}

return {
    Categories = Categories,
    Towers = {
        --Ring 0
        { name = "TNF",  category = "Ring0", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToG",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToME",  category = "Ring0", suggestedTime = { min = "5", sec = "0" } },
        { name = "ToB",  category = "Ring0", suggestedTime = { min = "5", sec = "0" } },
        { name = "ToVP",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCD",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBM",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoV",  category = "Ring0", suggestedTime = { min = "15", sec = "30" } },
        { name = "ToNSA",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToKTS",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDAN",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToKP",  category = "Ring0", suggestedTime = { min = "3", sec = "5" } },
        --Ring 1
        { name = "NEAT",  category = "Ring1", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToAST", category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToA",   category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToM",   category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToNI",  category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToH",   category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToK",   category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToKY",  category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToS",   category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSP",  category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSP:SE", category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToR",   category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIE",  category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoLS",  category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoLS:SE", category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTS",  category = "Ring1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIG",  category = "Ring1", suggestedTime = { min = "5", sec = "0" } },
        --Ring 2
        { name = "MAT",  category = "Ring2", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToPS",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBH",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToOH",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCH",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToT",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSD",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTF",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToES",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoWS",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDC",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFaF",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDD",  category = "Ring2", suggestedTime = { min = "3", sec = "5" } },
        --Ring 3
        { name = "ToFT",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIC",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAT",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDS",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToF",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWER",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSI",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWH",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToLD",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToD",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoHaD",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        { name = "TAT",  category = "Ring3", suggestedTime = { min = "0", sec = "30" } },
        { name = "ToC",  category = "Ring3", suggestedTime = { min = "3", sec = "5" } },
        --Ring 4
        { name = "ToSH",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToGG",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTM",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToE",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToL",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToLL",  category = "Ring4", suggestedTime = { min = "3", sec = "10" } },
        { name = "WBAT",  category = "Ring4", suggestedTime = { min = "0", sec = "10" } },
        { name = "ToDaD",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToHF",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoU",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToNP",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCN",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToVS",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToI",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToO",  category = "Ring4", suggestedTime = { min = "3", sec = "5" } },
        --Ring 5
        { name = "ToNV",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "LAT",  category = "Ring5", suggestedTime = { min = "0", sec = "10" } },
        { name = "ToTR",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRS",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDM",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToOC",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFF",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToEA",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTH",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToGaH",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoCR",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIB",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFN",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFO",  category = "Ring5", suggestedTime = { min = "3", sec = "5" } },
        { name = "R14MTR",  category = "Ring5", suggestedTime = { min = "0", sec = "50" } },
        --Ring 6
        { name = "ToFJ",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToEP",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRR",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTI",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToISC",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToN",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoSR",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIM",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSM",  category = "Ring6", suggestedTime = { min = "3", sec = "5" } },
        --Ring 7
        { name = "ToER",  category = "Ring7", suggestedTime = { min = "3", sec = "30" } },
        { name = "ToEH",  category = "Ring7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTB",  category = "Ring7", suggestedTime = { min = "3", sec = "5" } },
        { name = "FFAST",  category = "Ring7", suggestedTime = { min = "0", sec = "5" } },
        { name = "CoTE",  category = "Ring7", suggestedTime = { min = "15", sec = "30" } },
        --Ring 8
        { name = "ToGF",  category = "Ring8", suggestedTime = { min = "6", sec = "0" } },
        --Ring 9
        { name = "ToGO",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBBB",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToQT",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoL",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToPP",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToHA",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBT",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCA",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToNS",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCP",  category = "Ring9", suggestedTime = { min = "5", sec = "30" } },
        { name = "ToFaCT",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBK",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToJE",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAM",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCR",  category = "Ring9", suggestedTime = { min = "3", sec = "5" } },
        --Zone 1
        { name = "SAT",  category = "Zone1", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToZD",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTL",  category = "Zone1", suggestedTime = { min = "1", sec = "0" } },
        { name = "ToPHaT",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAD",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToP",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToMH",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToHS",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCO",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToYS",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAV",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWEL",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToUT",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToED",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRNI",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToZ",  category = "Zone1", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoP",  category = "Zone1", suggestedTime = { min = "15", sec = "30" } },
        --Zone 2
        { name = "ToDT",  category = "Zone2", suggestedTime = { min = "5", sec = "0" } },
        { name = "ToVR",  category = "Zone2", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSA",  category = "Zone2", suggestedTime = { min = "3", sec = "5" } },
        --Zone 3
        { name = "ToHH",  category = "Zone3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToOD",  category = "Zone3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCOF",  category = "Zone3", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBB",  category = "Zone3", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoTS",  category = "Zone3", suggestedTime = { min = "15", sec = "30" } },
        --Zone 7
        { name = "ToFM",  category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToUA",  category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToJ",    category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRW",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSV",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBR",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDF",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToGM",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCE",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWS",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToY",    category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCMC",  category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSaPS", category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToUI",   category = "Zone7", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoACT",  category = "Zone7", suggestedTime = { min = "15", sec = "30" } },
        --Zone 8
        { name = "ToDIE",  category = "Zone8", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoPE",  category = "Zone8", suggestedTime = { min = "15", sec = "30" } },
        { name = "ToAE",  category = "Zone8", suggestedTime = { min = "3", sec = "5" } },
        --Zone 9
        { name = "ToEMP",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToABCD",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDTD",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBL",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSRD",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToNN",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFCB",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFU",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToEC",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBBBB",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToMF",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoIC",  category = "Zone9", suggestedTime = { min = "15", sec = "30" } },
        { name = "ToVITE",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToHR",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToPB",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWWW",  category = "Zone9", suggestedTime = { min = "3", sec = "5" } },
        --Forgotten Ridge
        { name = "TIPAT",  category = "ForgottenRidge", suggestedTime = { min = "0", sec = "10" } },
        { name = "SoMD",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "ToJGF",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "SoLW",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoP",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoUR",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "ToII",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "SoWP",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "ToV",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTC",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "SoC",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoHP",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "0" } },
        { name = "ToIS",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDE",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoWN",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToMB",  category = "ForgottenRidge", suggestedTime = { min = "3", sec = "0" } },
        { name = "SoTP",  category = "ForgottenRidge", suggestedTime = { min = "2", sec = "50" } },
        --Garden of Eeshöl
        { name = "SoBJ",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoDS",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoIF",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoO",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoN",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoOA",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoGP",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoFF",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoLIQ",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoVV",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "SoFW",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        { name = "NEAF",  category = "GardenOfEeshol", suggestedTime = { min = "0", sec = "30" } },
        { name = "ToPA",  category = "GardenOfEeshol", suggestedTime = { min = "3", sec = "0" } },
        { name = "SoBA",  category = "GardenOfEeshol", suggestedTime = { min = "2", sec = "0" } },
        --Pit of Misery
        { name = "ToMDC",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "WAT",  category = "Pit-of-Misery", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToG",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToGF",  category = "Pit-of-Misery", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToVH",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToTH",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToTRP",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToEV",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToWM",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToBF",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        { name = "ToSF",  category = "Pit-of-Misery", suggestedTime = { min = "5", sec = "5" } },
        --The Eternal Abyss
        { name = "ToMH",  category = "TheEternalAbyss", suggestedTime = { min = "16", sec = "5" } },
        --TimelessManor
        { name = "ToDC",  category = "TimelessManor", suggestedTime = { min = "5", sec = "5" } },
        --100M Event Replay
        { name = "100MC",  category = "100M-Event-Replay", suggestedTime = { min = "0", sec = "10" } },
        { name = "100MT",  category = "100M-Event-Replay", suggestedTime = { min = "0", sec = "10" } },
        { name = "100MF",  category = "100M-Event-Replay", suggestedTime = { min = "0", sec = "30" } },
        { name = "100MR",  category = "100M-Event-Replay", suggestedTime = { min = "2", sec = "30" } },
        --BIOUMS
        { name = "MS",  category = "BIOUMS", suggestedTime = { min = "3", sec = "5" } },
        -- Merged from cslp1/Project-EToH-Script
        -- Arcane Area
        { name = "SoAS",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoRO",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoAP",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoBT",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoTC",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoME",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoCA",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoWC",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoMC",  category = "ArcaneArea", suggestedTime = { min = "2", sec = "50" } },
        { name = "ToIA",  category = "ArcaneArea", suggestedTime = { min = "3", sec = "5" } },
        -- Ashen Towerworks
        { name = "ToFZ",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWF",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCB",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCWC", category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFSF", category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToLLL", category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToMD",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRH",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSR",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToVT",  category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWIA", category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWMT", category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWoW", category = "AshenTowerworks", suggestedTime = { min = "3", sec = "5" } },
        -- Elysian Fields
        { name = "SoGE",  category = "ElysianFields", suggestedTime = { min = "2", sec = "50" } },
        -- Heccfire Depths
        { name = "SoRP",  category = "HeccfireDepths", suggestedTime = { min = "2", sec = "50" } },
        -- Legacy Fortress
        { name = "ToC(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToUB(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToPS(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToG(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToT(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToGI(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToMD(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToST(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTE(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTU(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToUP(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWS(L)",  category = "LegacyFortress", suggestedTime = { min = "3", sec = "5" } },
        -- Lost River
        { name = "ToEW",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoIS",  category = "LostRiver", suggestedTime = { min = "15", sec = "30" } },
        { name = "ToUH",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTST",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToLOZ",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDL",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToOO",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCS",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWaW",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTJ",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTEM",  category = "LostRiver", suggestedTime = { min = "3", sec = "5" } },
        -- Paradise Atoll
        { name = "SoUV",  category = "ParadiseAtoll", suggestedTime = { min = "2", sec = "50" } },
        -- Silent Abyss
        { name = "ToTINT",  category = "SilentAbyss", suggestedTime = { min = "3", sec = "5" } },
        { name = "SoMB",  category = "SilentAbyss", suggestedTime = { min = "2", sec = "50" } },
        { name = "SoMA",  category = "SilentAbyss", suggestedTime = { min = "2", sec = "50" } },
        -- Steelspire Horizon
        { name = "ToQR",  category = "SteelspireHorizon", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSaT",  category = "SteelspireHorizon", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSL",  category = "SteelspireHorizon", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFH",  category = "SteelspireHorizon", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToCBTS",  category = "SteelspireHorizon", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTFC",  category = "SteelspireHorizon", suggestedTime = { min = "3", sec = "5" } },
        -- Summit of Memories
        { name = "ToAST(C)",  category = "SummitOfMemories", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToA(C)",  category = "SummitOfMemories", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFT(C)",  category = "SummitOfMemories", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToPHaT(C)",  category = "SummitOfMemories", suggestedTime = { min = "3", sec = "5" } },
        { name = "TT(C)",  category = "SummitOfMemories", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDC(C)",  category = "SummitOfMemories", suggestedTime = { min = "3", sec = "5" } },
        -- The Doghouse
        { name = "MCoMC",  category = "TheDoghouse", suggestedTime = { min = "2", sec = "0" } },
        -- XL Ring 1
        { name = "CoA",     category = "XLRing1", suggestedTime = { min = "15", sec = "30" } },
        { name = "CoIG",    category = "XLRing1", suggestedTime = { min = "15", sec = "30" } },
        { name = "CoR",     category = "XLRing1", suggestedTime = { min = "15", sec = "30" } },
        -- XL Ring 3
        { name = "CoUC",    category = "XLRing3", suggestedTime = { min = "15", sec = "30" } },
        -- XL Ring 5
        { name = "CoIB",    category = "XLRing5", suggestedTime = { min = "15", sec = "30" } },
        -- Zone 4
        { name = "ToFSC",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAC",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFaST",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToUID",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToET",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToWW",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToPC",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToMIM",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToSS",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToDDD",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToFG",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIF",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "CoQ",  category = "Zone4", suggestedTime = { min = "15", sec = "30" } },
        { name = "ToTV",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAAA",  category = "Zone4", suggestedTime = { min = "3", sec = "5" } },
        -- Zone 5
        { name = "ToPZ",  category = "Zone5", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToAR",  category = "Zone5", suggestedTime = { min = "3", sec = "5" } },
        -- Zone 6
        { name = "ToMM",  category = "Zone6", suggestedTime = { min = "3", sec = "5" } },
        -- Zone 10
        { name = "ToCZ",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRL",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToIT",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToVV",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRoMW",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToTHT",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToBP",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
        { name = "ToRT",  category = "Zone10", suggestedTime = { min = "3", sec = "5" } },
    },
    TowerRush = {
        { name = "R1TR", category = "Ring1", suggestedTime = { min = "39", sec = "0" }, isTowerRush = true, },
        { name = "R3TR", category = "Ring3", suggestedTime = { min = "39", sec = "0" }, isTowerRush = true, },
        { name = "R5TR", category = "Ring5", suggestedTime = { min = "33", sec = "0" }, isTowerRush = true, },
        { name = "R9TR", category = "Ring9", suggestedTime = { min = "40", sec = "0" }, isTowerRush = true, },
        { name = "GoETR", category = "GardenOfEeshol", suggestedTime = { min = "27", sec = "0" }, isTowerRush = true, },
        { name = "PoMTR", category = "Pit-of-Misery", places = 15639952229, suggestedTime = { min = "200", sec = "0" }, isTowerRush = true, },
        -- Merged from cslp1/Project-EToH-Script
        { name = "PTR", category = "Ring0", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "R2TR", category = "Ring2", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "R4TR", category = "Ring4", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "LRTR", category = "LostRiver", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "ATwTR", category = "AshenTowerworks", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "AATR", category = "ArcaneArea", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "Z4TR", category = "Zone4", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "Z7TR", category = "Zone7", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "Z9TR", category = "Zone9", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "LFTR", category = "LegacyFortress", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
        { name = "Z1TR", category = "Zone1", suggestedTime = { min = "60", sec = "0" }, isTowerRush = true, },
    },
}
